# Generated by Django 4.0.10 on 2023-03-25 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_boards_allowed_to_alter_boards_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskdata',
            name='board',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='status',
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='task.boards')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taskdata',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='task.tasklist'),
        ),
    ]
